import { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { motion, AnimatePresence } from "framer-motion";
import { Check, Calendar, MapPin, MessageSquare, Phone, Mail, User, CreditCard, Loader2 } from "lucide-react";

interface BookingModalProps {
  isOpen: boolean;
  onClose: () => void;
  selectedService?: string;
  services?: Array<{
    title: string;
    icon: string;
    description: string;
    services: string[];
    image?: string;
    price?: string;
    priceRange?: { min: number; max: number };
  }>;
}

const BookingModal = ({ isOpen, onClose, selectedService, services = [] }: BookingModalProps) => {
  const { toast } = useToast();
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    phone: "",
    address: "",
    service: selectedService || "",
    message: ""
  });
  const [isProcessingPayment, setIsProcessingPayment] = useState(false);
  const [paymentAmount, setPaymentAmount] = useState<number | null>(null);
  const [acceptTerms, setAcceptTerms] = useState(false);

  const serviceOptions = services.length > 0 
    ? services.map(service => service.title)
    : [
        "Plumbing Services",
        "Painting Services", 
        "Waterproofing",
        "Carpentry Work",
        "Architectural Consultancy"
      ];

  // Load Razorpay script
  const loadRazorpayScript = () => {
    return new Promise((resolve) => {
      const script = document.createElement('script');
      script.src = 'https://checkout.razorpay.com/v1/checkout.js';
      script.onload = () => resolve(true);
      script.onerror = () => resolve(false);
      document.body.appendChild(script);
    });
  };

  // Initialize Razorpay payment
  const initializePayment = async (amount: number, bookingData: any) => {
    const scriptLoaded = await loadRazorpayScript();
    if (!scriptLoaded) {
      toast({
        title: "Error",
        description: "Payment gateway failed to load. Please try again.",
        variant: "destructive"
      });
      return;
    }

    const options = {
      key: import.meta.env.VITE_RAZORPAY_KEY_ID || 'rzp_test_1234567890', // Replace with your Razorpay key
      amount: amount * 100, // Convert to paise
      currency: 'INR',
      name: 'Tricity Solutions',
      description: `Booking for ${bookingData.service}`,
      image: '/logo1.png',
      order_id: '', // This will be generated by your backend
      handler: async (response: any) => {
        // Payment successful, now create the booking
        await createBooking(bookingData, response);
      },
      prefill: {
        name: bookingData.name,
        email: bookingData.email,
        contact: bookingData.phone,
      },
      notes: {
        address: bookingData.address,
        service: bookingData.service,
        message: bookingData.message,
      },
      theme: {
        color: '#3B82F6',
      },
      modal: {
        ondismiss: () => {
          setIsProcessingPayment(false);
        }
      }
    };

    const razorpay = new (window as any).Razorpay(options);
    razorpay.open();
  };

  // Create booking after successful payment
  const createBooking = async (bookingData: any, paymentResponse: any) => {
    try {
      const apiBase = (import.meta as any).env?.VITE_API_BASE_URL;
      const enableSync = Boolean((import.meta as any).env?.DEV ?? true);
      const baseUrl = apiBase ? `${apiBase}/api/bookings` : `/api/bookings`;
      const url = enableSync ? `${baseUrl}?sync=1` : baseUrl;
      
      const res = await fetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: bookingData.name,
          email: bookingData.email,
          phone: bookingData.phone,
          address: bookingData.address,
          service: bookingData.service,
          message: bookingData.message,
          payment: {
            razorpay_payment_id: paymentResponse.razorpay_payment_id,
            razorpay_order_id: paymentResponse.razorpay_order_id,
            razorpay_signature: paymentResponse.razorpay_signature,
            amount: paymentAmount
          }
        })
      });

      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        throw new Error(data.error || "Failed to create booking after payment");
      }

      const data = await res.json();
      toast({
        title: "Payment & Booking Successful!",
        description: `Your payment has been processed and booking confirmed. Booking ID: ${data.bookingId}`,
      });

      // Reset form and close modal
      setFormData({
        name: "",
        email: "",
        phone: "",
        address: "",
        service: "",
        message: ""
      });
      setPaymentAmount(null);
      setIsProcessingPayment(false);
      onClose();
    } catch (error: any) {
      toast({
        title: "Booking Failed",
        description: error?.message || "Payment successful but booking failed. Please contact support.",
        variant: "destructive"
      });
      setIsProcessingPayment(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    // Basic validation
    if (!formData.name || !formData.phone || !formData.service) {
      toast({
        title: "Error",
        description: "Please fill in all required fields.",
        variant: "destructive"
      });
      return;
    }

    // Terms & Conditions validation
    if (!acceptTerms) {
      toast({
        title: "Error",
        description: "Please accept the Terms & Conditions to proceed.",
        variant: "destructive"
      });
      return;
    }

    // Get pricing for the selected service
    const selectedServiceData = services.find(s => s.title === formData.service);
    if (!selectedServiceData?.priceRange) {
      toast({
        title: "Error",
        description: "Please select a valid service.",
        variant: "destructive"
      });
      return;
    }

    // 40% booking fee for all services (₹400 out of ₹1000)
    const bookingFeeAmount = 400;
    setPaymentAmount(bookingFeeAmount);
    setIsProcessingPayment(true);

    // Initialize payment
    await initializePayment(bookingFeeAmount, formData);
  };

  const handleInputChange = (field: string, value: string) => {
    setFormData(prev => ({
      ...prev,
      [field]: value
    }));
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-md max-h-[80vh] overflow-y-auto bg-gradient-to-br from-background to-background/95 backdrop-blur-sm border-primary/10 shadow-xl">
        <DialogHeader>
          <DialogTitle className="text-2xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-primary to-secondary text-center">
            Book Our Services
          </DialogTitle>
          <div className="h-1 w-24 mx-auto mt-2 bg-gradient-to-r from-primary to-secondary rounded-full"></div>
        </DialogHeader>
        
        <motion.form 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, staggerChildren: 0.1 }}
          onSubmit={handleSubmit} 
          className="space-y-5 mt-4">
          <motion.div 
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="name" className="flex items-center gap-2 text-foreground/80">
                <User size={16} className="text-primary" /> Full Name *
              </Label>
              <Input
                id="name"
                value={formData.name}
                onChange={(e) => handleInputChange("name", e.target.value)}
                placeholder="Enter your name"
                required
                className="border-primary/20 focus:border-primary focus:ring-primary/20 transition-all duration-300"
              />
            </div>
            
            <div className="space-y-2">
              <Label htmlFor="phone" className="flex items-center gap-2 text-foreground/80">
                <Phone size={16} className="text-primary" /> Phone Number *
              </Label>
              <Input
                id="phone"
                type="tel"
                value={formData.phone}
                onChange={(e) => handleInputChange("phone", e.target.value)}
                placeholder="+91 98765 43210"
                required
                className="border-primary/20 focus:border-primary focus:ring-primary/20 transition-all duration-300"
              />
            </div>
          </motion.div>

          <motion.div 
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="space-y-2">
            <Label htmlFor="email" className="flex items-center gap-2 text-foreground/80">
              <Mail size={16} className="text-primary" /> Email Address
            </Label>
            <Input
              id="email"
              type="email"
              value={formData.email}
              onChange={(e) => handleInputChange("email", e.target.value)}
              placeholder="your.email@example.com"
              className="border-primary/20 focus:border-primary focus:ring-primary/20 transition-all duration-300"
            />
          </motion.div>

          <motion.div 
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3 }}
            className="space-y-2">
            <Label htmlFor="service" className="flex items-center gap-2 text-foreground/80">
              <Check size={16} className="text-primary" /> Type of Service *
            </Label>
            <Select value={formData.service} onValueChange={(value) => handleInputChange("service", value)}>
              <SelectTrigger className="border-primary/20 focus:border-primary focus:ring-primary/20 transition-all duration-300">
                <SelectValue placeholder="Select a service" />
              </SelectTrigger>
              <SelectContent>
                {serviceOptions.map((service) => {
                  const serviceData = services.find(s => s.title === service);
                  return (
                    <SelectItem key={service} value={service}>
                      <div className="flex items-center justify-between w-full">
                        <span>{service}</span>
                        {serviceData?.price && (
                          <span className="text-green-600 font-medium text-sm ml-2">
                            {serviceData.price}
                          </span>
                        )}
                      </div>
                    </SelectItem>
                  );
                })}
              </SelectContent>
            </Select>
            
            {/* Pricing Information */}
            {formData.service && (() => {
              const selectedServiceData = services.find(s => s.title === formData.service);
              return selectedServiceData?.price ? (
                <motion.div
                  initial={{ opacity: 0, height: 0 }}
                  animate={{ opacity: 1, height: "auto" }}
                  transition={{ delay: 0.1 }}
                  className="mt-3 p-4 bg-gradient-to-r from-green-50 to-emerald-50 dark:from-green-900/20 dark:to-emerald-900/20 rounded-lg border border-green-200 dark:border-green-800"
                >
                  <div className="flex items-center gap-2 mb-3">
                    <span className="text-green-600 dark:text-green-400 text-lg">💰</span>
                    <span className="text-sm font-medium text-green-700 dark:text-green-300">
                      Service Pricing
                    </span>
                  </div>
                  
                  {/* Total Cost */}
                  <div className="text-center mb-3 p-2 bg-white/50 dark:bg-slate-800/50 rounded-lg">
                    <div className="text-2xl font-bold text-green-600 dark:text-green-400">
                      {selectedServiceData.price}
                    </div>
                    <div className="text-xs text-green-500 dark:text-green-500">
                      Total Service Cost
                    </div>
                  </div>
                  
                  {/* Payment Breakdown */}
                  <div className="grid grid-cols-2 gap-3">
                    <div className="bg-blue-50 dark:bg-blue-900/20 p-3 rounded-lg border border-blue-200 dark:border-blue-800">
                      <div className="text-center">
                        <div className="text-xs text-blue-600 dark:text-blue-400 font-medium mb-1">Pay Now</div>
                        <div className="text-lg font-bold text-blue-700 dark:text-blue-300">₹400</div>
                        <div className="text-xs text-blue-500 dark:text-blue-500">40% booking fee</div>
                      </div>
                    </div>
                    <div className="bg-orange-50 dark:bg-orange-900/20 p-3 rounded-lg border border-orange-200 dark:border-orange-800">
                      <div className="text-center">
                        <div className="text-xs text-orange-600 dark:text-orange-400 font-medium mb-1">After Service</div>
                        <div className="text-lg font-bold text-orange-700 dark:text-orange-300">₹600</div>
                        <div className="text-xs text-orange-500 dark:text-orange-500">60% remaining</div>
                      </div>
                    </div>
                  </div>
                </motion.div>
              ) : null;
            })()}
          </motion.div>

          <motion.div 
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.4 }}
            className="space-y-2">
            <Label htmlFor="address" className="flex items-center gap-2 text-foreground/80">
              <MapPin size={16} className="text-primary" /> Service Address
            </Label>
            <Textarea
              id="address"
              value={formData.address}
              onChange={(e) => handleInputChange("address", e.target.value)}
              placeholder="Enter the address where service is needed"
              rows={2}
              className="border-primary/20 focus:border-primary focus:ring-primary/20 transition-all duration-300"
            />
          </motion.div>

          <motion.div 
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.5 }}
            className="space-y-2">
            <Label htmlFor="message" className="flex items-center gap-2 text-foreground/80">
              <MessageSquare size={16} className="text-primary" /> Additional Details
            </Label>
            <Textarea
              id="message"
              value={formData.message}
              onChange={(e) => handleInputChange("message", e.target.value)}
              placeholder="Tell us more about your requirements..."
              rows={3}
              className="border-primary/20 focus:border-primary focus:ring-primary/20 transition-all duration-300"
            />
          </motion.div>

          {/* Payment Summary */}
          {formData.service && (() => {
            const selectedServiceData = services.find(s => s.title === formData.service);
            return selectedServiceData?.priceRange ? (
              <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.55 }}
                className="p-4 bg-gradient-to-r from-blue-50 to-indigo-50 dark:from-blue-900/20 dark:to-indigo-900/20 rounded-lg border border-blue-200 dark:border-blue-800"
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <CreditCard className="w-5 h-5 text-blue-600 dark:text-blue-400" />
                    <span className="font-medium text-blue-700 dark:text-blue-300">Payment Required</span>
                  </div>
                  <div className="text-right">
                    <div className="text-xl font-bold text-blue-600 dark:text-blue-400">
                      ₹400
                    </div>
                    <div className="text-xs text-blue-500 dark:text-blue-500">
                      40% booking fee
                    </div>
                  </div>
                </div>
                <div className="mt-2 text-xs text-blue-600 dark:text-blue-400">
                  Service Cost: ₹1000 • Booking Fee: ₹400 (40%) • After Service: ₹600 (60%) • Secure payment via Razorpay
                </div>
              </motion.div>
            ) : null;
          })()}

          {/* Terms & Conditions */}
          <motion.div 
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.5 }}
            className="pt-4">
            <div className="flex items-start gap-3 p-3 bg-slate-50 dark:bg-slate-800/50 rounded-lg border border-slate-200 dark:border-slate-700">
              <input
                type="checkbox"
                id="acceptTerms"
                checked={acceptTerms}
                onChange={(e) => setAcceptTerms(e.target.checked)}
                className="mt-1 w-4 h-4 text-primary bg-white border-slate-300 rounded focus:ring-primary focus:ring-2"
              />
              <div className="text-sm text-slate-600 dark:text-slate-300">
                <label htmlFor="acceptTerms" className="cursor-pointer">
                  I agree to the{" "}
                  <span className="text-primary hover:underline font-medium">
                    Terms & Conditions
                  </span>{" "}
                  and{" "}
                  <span className="text-primary hover:underline font-medium">
                    Privacy Policy
                  </span>
                  . I understand that:
                  <ul className="mt-2 ml-4 space-y-1 text-xs">
                    <li>• ₹400 booking fee is non-refundable</li>
                    <li>• Remaining ₹600 is due after service completion</li>
                    <li>• Service will be scheduled within 24-48 hours</li>
                    <li>• Cancellation policy applies as per T&C</li>
                  </ul>
                </label>
              </div>
            </div>
          </motion.div>

          <motion.div 
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.6 }}
            className="flex gap-3 pt-6">
            <Button 
              type="button" 
              variant="outline" 
              onClick={onClose} 
              className="flex-1 border-primary/20 hover:bg-primary/5 transition-all duration-300"
            >
              Cancel
            </Button>
            <Button 
              type="submit" 
              disabled={isProcessingPayment}
              className="flex-1 bg-gradient-to-r from-primary to-secondary hover:opacity-90 text-white font-medium transition-all duration-300 hover:shadow-lg hover:shadow-primary/20 hover:-translate-y-0.5 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {isProcessingPayment ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Processing Payment...
                </>
              ) : (
                <>
                  <CreditCard className="w-4 h-4 mr-2" />
                  {paymentAmount ? `Pay ₹${paymentAmount} & Book` : 'Pay and Book'}
                </>
              )}
            </Button>
          </motion.div>
        </motion.form>
      </DialogContent>
    </Dialog>
  );
};

export default BookingModal;